// RenderFrameMetadata.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     cc/mojom/render_frame_metadata.mojom
//

package org.chromium.cc.mojom;

import androidx.annotation.IntDef;


public final class RenderFrameMetadata extends org.chromium.mojo.bindings.Struct {

    private static final int STRUCT_SIZE = 136;
    private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(136, 0)};
    private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    public int rootBackgroundColor;
    public org.chromium.gfx.mojom.PointF rootScrollOffset;
    public boolean isScrollOffsetAtTop;
    public org.chromium.viz.mojom.Selection selection;
    public boolean isMobileOptimized;
    public DelegatedInkBrowserMetadata delegatedInkMetadata;
    public float deviceScaleFactor;
    public org.chromium.gfx.mojom.Size viewportSizeInPixels;
    public org.chromium.viz.mojom.LocalSurfaceId localSurfaceId;
    public float pageScaleFactor;
    public float externalPageScaleFactor;
    public float topControlsHeight;
    public float topControlsShownRatio;
    public int newVerticalScrollDirection;
    public org.chromium.mojo_base.mojom.TimeDelta previousSurfacesVisualUpdateDuration;
    public org.chromium.mojo_base.mojom.TimeDelta currentSurfaceVisualUpdateDuration;
    public float bottomControlsHeight;
    public float bottomControlsShownRatio;
    public float topControlsMinHeightOffset;
    public float bottomControlsMinHeightOffset;
    public float minPageScaleFactor;
    public float maxPageScaleFactor;
    public boolean rootOverflowYHidden;
    public org.chromium.gfx.mojom.SizeF scrollableViewportSize;
    public org.chromium.gfx.mojom.SizeF rootLayerSize;
    public boolean hasTransparentBackground;

    private RenderFrameMetadata(int version) {
        super(STRUCT_SIZE, version);
    }

    public RenderFrameMetadata() {
        this(0);
    }

    public static RenderFrameMetadata deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message));
    }

    /**
     * Similar to the method above, but deserializes from a |ByteBuffer| instance.
     *
     * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
     */
    public static RenderFrameMetadata deserialize(java.nio.ByteBuffer data) {
        return deserialize(new org.chromium.mojo.bindings.Message(
                data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
    }

    @SuppressWarnings("unchecked")
    public static RenderFrameMetadata decode(org.chromium.mojo.bindings.Decoder decoder0) {
        if (decoder0 == null) {
            return null;
        }
        decoder0.increaseStackDepth();
        RenderFrameMetadata result;
        try {
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            final int elementsOrVersion = mainDataHeader.elementsOrVersion;
            result = new RenderFrameMetadata(elementsOrVersion);
                {
                    
                result.rootBackgroundColor = decoder0.readInt(8);
                }
                {
                    
                result.isScrollOffsetAtTop = decoder0.readBoolean(12, 0);
                }
                {
                    
                result.isMobileOptimized = decoder0.readBoolean(12, 1);
                }
                {
                    
                result.rootOverflowYHidden = decoder0.readBoolean(12, 2);
                }
                {
                    
                result.hasTransparentBackground = decoder0.readBoolean(12, 3);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(16, true);
                result.rootScrollOffset = org.chromium.gfx.mojom.PointF.decode(decoder1);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(24, false);
                result.selection = org.chromium.viz.mojom.Selection.decode(decoder1);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(32, true);
                result.delegatedInkMetadata = DelegatedInkBrowserMetadata.decode(decoder1);
                }
                {
                    
                result.deviceScaleFactor = decoder0.readFloat(40);
                }
                {
                    
                result.pageScaleFactor = decoder0.readFloat(44);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(48, false);
                result.viewportSizeInPixels = org.chromium.gfx.mojom.Size.decode(decoder1);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(56, true);
                result.localSurfaceId = org.chromium.viz.mojom.LocalSurfaceId.decode(decoder1);
                }
                {
                    
                result.externalPageScaleFactor = decoder0.readFloat(64);
                }
                {
                    
                result.topControlsHeight = decoder0.readFloat(68);
                }
                {
                    
                result.topControlsShownRatio = decoder0.readFloat(72);
                }
                {
                    
                result.newVerticalScrollDirection = decoder0.readInt(76);
                    org.chromium.viz.mojom.VerticalScrollDirection.validate(result.newVerticalScrollDirection);
                    result.newVerticalScrollDirection = org.chromium.viz.mojom.VerticalScrollDirection.toKnownValue(result.newVerticalScrollDirection);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(80, false);
                result.previousSurfacesVisualUpdateDuration = org.chromium.mojo_base.mojom.TimeDelta.decode(decoder1);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(88, false);
                result.currentSurfaceVisualUpdateDuration = org.chromium.mojo_base.mojom.TimeDelta.decode(decoder1);
                }
                {
                    
                result.bottomControlsHeight = decoder0.readFloat(96);
                }
                {
                    
                result.bottomControlsShownRatio = decoder0.readFloat(100);
                }
                {
                    
                result.topControlsMinHeightOffset = decoder0.readFloat(104);
                }
                {
                    
                result.bottomControlsMinHeightOffset = decoder0.readFloat(108);
                }
                {
                    
                result.minPageScaleFactor = decoder0.readFloat(112);
                }
                {
                    
                result.maxPageScaleFactor = decoder0.readFloat(116);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(120, false);
                result.scrollableViewportSize = org.chromium.gfx.mojom.SizeF.decode(decoder1);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(128, false);
                result.rootLayerSize = org.chromium.gfx.mojom.SizeF.decode(decoder1);
                }

        } finally {
            decoder0.decreaseStackDepth();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
        org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
        
        encoder0.encode(this.rootBackgroundColor, 8);
        
        encoder0.encode(this.isScrollOffsetAtTop, 12, 0);
        
        encoder0.encode(this.isMobileOptimized, 12, 1);
        
        encoder0.encode(this.rootOverflowYHidden, 12, 2);
        
        encoder0.encode(this.hasTransparentBackground, 12, 3);
        
        encoder0.encode(this.rootScrollOffset, 16, true);
        
        encoder0.encode(this.selection, 24, false);
        
        encoder0.encode(this.delegatedInkMetadata, 32, true);
        
        encoder0.encode(this.deviceScaleFactor, 40);
        
        encoder0.encode(this.pageScaleFactor, 44);
        
        encoder0.encode(this.viewportSizeInPixels, 48, false);
        
        encoder0.encode(this.localSurfaceId, 56, true);
        
        encoder0.encode(this.externalPageScaleFactor, 64);
        
        encoder0.encode(this.topControlsHeight, 68);
        
        encoder0.encode(this.topControlsShownRatio, 72);
        
        encoder0.encode(this.newVerticalScrollDirection, 76);
        
        encoder0.encode(this.previousSurfacesVisualUpdateDuration, 80, false);
        
        encoder0.encode(this.currentSurfaceVisualUpdateDuration, 88, false);
        
        encoder0.encode(this.bottomControlsHeight, 96);
        
        encoder0.encode(this.bottomControlsShownRatio, 100);
        
        encoder0.encode(this.topControlsMinHeightOffset, 104);
        
        encoder0.encode(this.bottomControlsMinHeightOffset, 108);
        
        encoder0.encode(this.minPageScaleFactor, 112);
        
        encoder0.encode(this.maxPageScaleFactor, 116);
        
        encoder0.encode(this.scrollableViewportSize, 120, false);
        
        encoder0.encode(this.rootLayerSize, 128, false);
    }
}