// AnnotationAgentContainer_Internal.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/annotation/annotation.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


class AnnotationAgentContainer_Internal {

    public static final org.chromium.mojo.bindings.Interface.Manager<AnnotationAgentContainer, AnnotationAgentContainer.Proxy> MANAGER =
            new org.chromium.mojo.bindings.Interface.Manager<AnnotationAgentContainer, AnnotationAgentContainer.Proxy>() {

        @Override
        public String getName() {
            return "blink.mojom.AnnotationAgentContainer";
        }

        @Override
        public int getVersion() {
          return 0;
        }

        @Override
        public Proxy buildProxy(org.chromium.mojo.system.Core core,
                                org.chromium.mojo.bindings.MessageReceiverWithResponder messageReceiver) {
            return new Proxy(core, messageReceiver);
        }

        @Override
        public Stub buildStub(org.chromium.mojo.system.Core core, AnnotationAgentContainer impl) {
            return new Stub(core, impl);
        }

        @Override
        public AnnotationAgentContainer[] buildArray(int size) {
          return new AnnotationAgentContainer[size];
        }
    };


    private static final int CREATE_AGENT_ORDINAL = 0;


    static final class Proxy extends org.chromium.mojo.bindings.Interface.AbstractProxy implements AnnotationAgentContainer.Proxy {

        Proxy(org.chromium.mojo.system.Core core,
              org.chromium.mojo.bindings.MessageReceiverWithResponder messageReceiver) {
            super(core, messageReceiver);
        }


        @Override
        public void createAgent(
AnnotationAgentHost hostRemote, org.chromium.mojo.bindings.InterfaceRequest<AnnotationAgent> agentReceiver, int type, String serializedSelector) {

            AnnotationAgentContainerCreateAgentParams _message = new AnnotationAgentContainerCreateAgentParams();

            _message.hostRemote = hostRemote;

            _message.agentReceiver = agentReceiver;

            _message.type = type;

            _message.serializedSelector = serializedSelector;


            getProxyHandler().getMessageReceiver().accept(
                    _message.serializeWithHeader(
                            getProxyHandler().getCore(),
                            new org.chromium.mojo.bindings.MessageHeader(CREATE_AGENT_ORDINAL)));

        }


    }

    static final class Stub extends org.chromium.mojo.bindings.Interface.Stub<AnnotationAgentContainer> {

        Stub(org.chromium.mojo.system.Core core, AnnotationAgentContainer impl) {
            super(core, impl);
        }

        @Override
        public boolean accept(org.chromium.mojo.bindings.Message message) {
            try {
                org.chromium.mojo.bindings.ServiceMessage messageWithHeader =
                        message.asServiceMessage();
                org.chromium.mojo.bindings.MessageHeader header = messageWithHeader.getHeader();
                int flags = org.chromium.mojo.bindings.MessageHeader.NO_FLAG;
                if (header.hasFlag(org.chromium.mojo.bindings.MessageHeader.MESSAGE_IS_SYNC_FLAG)) {
                    flags = flags | org.chromium.mojo.bindings.MessageHeader.MESSAGE_IS_SYNC_FLAG;
                }
                if (!header.validateHeader(flags)) {
                    return false;
                }
                switch(header.getType()) {

                    case org.chromium.mojo.bindings.interfacecontrol.InterfaceControlMessagesConstants.RUN_OR_CLOSE_PIPE_MESSAGE_ID:
                        return org.chromium.mojo.bindings.InterfaceControlMessagesHelper.handleRunOrClosePipe(
                                AnnotationAgentContainer_Internal.MANAGER, messageWithHeader);





                    case CREATE_AGENT_ORDINAL: {

                        AnnotationAgentContainerCreateAgentParams data =
                                AnnotationAgentContainerCreateAgentParams.deserialize(messageWithHeader.getPayload());

                        getImpl().createAgent(data.hostRemote, data.agentReceiver, data.type, data.serializedSelector);
                        return true;
                    }


                    default:
                        return false;
                }
            } catch (org.chromium.mojo.bindings.DeserializationException e) {
                System.err.println(e.toString());
                return false;
            }
        }

        @Override
        public boolean acceptWithResponder(org.chromium.mojo.bindings.Message message, org.chromium.mojo.bindings.MessageReceiver receiver) {
            try {
                org.chromium.mojo.bindings.ServiceMessage messageWithHeader =
                        message.asServiceMessage();
                org.chromium.mojo.bindings.MessageHeader header = messageWithHeader.getHeader();
                int flags = org.chromium.mojo.bindings.MessageHeader.MESSAGE_EXPECTS_RESPONSE_FLAG;
                if (header.hasFlag(org.chromium.mojo.bindings.MessageHeader.MESSAGE_IS_SYNC_FLAG)) {
                    flags = flags | org.chromium.mojo.bindings.MessageHeader.MESSAGE_IS_SYNC_FLAG;
                }
                if (!header.validateHeader(flags)) {
                    return false;
                }
                switch(header.getType()) {

                    case org.chromium.mojo.bindings.interfacecontrol.InterfaceControlMessagesConstants.RUN_MESSAGE_ID:
                        return org.chromium.mojo.bindings.InterfaceControlMessagesHelper.handleRun(
                                getCore(), AnnotationAgentContainer_Internal.MANAGER, messageWithHeader, receiver);




                    default:
                        return false;
                }
            } catch (org.chromium.mojo.bindings.DeserializationException e) {
                System.err.println(e.toString());
                return false;
            }
        }
    }


    
    static final class AnnotationAgentContainerCreateAgentParams extends org.chromium.mojo.bindings.Struct {

        private static final int STRUCT_SIZE = 32;
        private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(32, 0)};
        private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
        public AnnotationAgentHost hostRemote;
        public org.chromium.mojo.bindings.InterfaceRequest<AnnotationAgent> agentReceiver;
        public int type;
        public String serializedSelector;

        private AnnotationAgentContainerCreateAgentParams(int version) {
            super(STRUCT_SIZE, version);
        }

        public AnnotationAgentContainerCreateAgentParams() {
            this(0);
        }

        public static AnnotationAgentContainerCreateAgentParams deserialize(org.chromium.mojo.bindings.Message message) {
            return decode(new org.chromium.mojo.bindings.Decoder(message));
        }

        /**
         * Similar to the method above, but deserializes from a |ByteBuffer| instance.
         *
         * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
         */
        public static AnnotationAgentContainerCreateAgentParams deserialize(java.nio.ByteBuffer data) {
            return deserialize(new org.chromium.mojo.bindings.Message(
                    data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
        }

        @SuppressWarnings("unchecked")
        public static AnnotationAgentContainerCreateAgentParams decode(org.chromium.mojo.bindings.Decoder decoder0) {
            if (decoder0 == null) {
                return null;
            }
            decoder0.increaseStackDepth();
            AnnotationAgentContainerCreateAgentParams result;
            try {
                org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
                final int elementsOrVersion = mainDataHeader.elementsOrVersion;
                result = new AnnotationAgentContainerCreateAgentParams(elementsOrVersion);
                    {
                        
                    result.hostRemote = decoder0.readServiceInterface(8, false, AnnotationAgentHost.MANAGER);
                    }
                    {
                        
                    result.agentReceiver = decoder0.readInterfaceRequest(16, false);
                    }
                    {
                        
                    result.type = decoder0.readInt(20);
                        AnnotationType.validate(result.type);
                        result.type = AnnotationType.toKnownValue(result.type);
                    }
                    {
                        
                    result.serializedSelector = decoder0.readString(24, false);
                    }

            } finally {
                decoder0.decreaseStackDepth();
            }
            return result;
        }

        @SuppressWarnings("unchecked")
        @Override
        protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
            org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
            
            encoder0.encode(this.hostRemote, 8, false, AnnotationAgentHost.MANAGER);
            
            encoder0.encode(this.agentReceiver, 16, false);
            
            encoder0.encode(this.type, 20);
            
            encoder0.encode(this.serializedSelector, 24, false);
        }
    }



}
