// BucketManagerHost.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/buckets/bucket_manager_host.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public interface BucketManagerHost extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends BucketManagerHost, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<BucketManagerHost, BucketManagerHost.Proxy> MANAGER = BucketManagerHost_Internal.MANAGER;

    void openBucket(
String name, BucketPolicies policy, 
OpenBucket_Response callback);

    interface OpenBucket_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<BucketHost> { }


    void keys(

Keys_Response callback);

    interface Keys_Response extends org.chromium.mojo.bindings.Callbacks.Callback2<String[], Boolean> { }


    void deleteBucket(
String name, 
DeleteBucket_Response callback);

    interface DeleteBucket_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Boolean> { }


}
