// BucketPolicies.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/buckets/bucket_manager_host.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public final class BucketPolicies extends org.chromium.mojo.bindings.Struct {

    private static final int STRUCT_SIZE = 32;
    private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(32, 0)};
    private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    public boolean persisted;
    public boolean hasPersisted;
    public int durability;
    public boolean hasDurability;
    public long quota;
    public boolean hasQuota;
    public org.chromium.mojo_base.mojom.Time expires;

    private BucketPolicies(int version) {
        super(STRUCT_SIZE, version);
        this.hasPersisted = (boolean) false;
        this.hasDurability = (boolean) false;
        this.hasQuota = (boolean) false;
    }

    public BucketPolicies() {
        this(0);
    }

    public static BucketPolicies deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message));
    }

    /**
     * Similar to the method above, but deserializes from a |ByteBuffer| instance.
     *
     * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
     */
    public static BucketPolicies deserialize(java.nio.ByteBuffer data) {
        return deserialize(new org.chromium.mojo.bindings.Message(
                data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
    }

    @SuppressWarnings("unchecked")
    public static BucketPolicies decode(org.chromium.mojo.bindings.Decoder decoder0) {
        if (decoder0 == null) {
            return null;
        }
        decoder0.increaseStackDepth();
        BucketPolicies result;
        try {
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            final int elementsOrVersion = mainDataHeader.elementsOrVersion;
            result = new BucketPolicies(elementsOrVersion);
                {
                    
                result.persisted = decoder0.readBoolean(8, 0);
                }
                {
                    
                result.hasPersisted = decoder0.readBoolean(8, 1);
                }
                {
                    
                result.hasDurability = decoder0.readBoolean(8, 2);
                }
                {
                    
                result.hasQuota = decoder0.readBoolean(8, 3);
                }
                {
                    
                result.durability = decoder0.readInt(12);
                    BucketDurability.validate(result.durability);
                    result.durability = BucketDurability.toKnownValue(result.durability);
                }
                {
                    
                result.quota = decoder0.readLong(16);
                }
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(24, true);
                result.expires = org.chromium.mojo_base.mojom.Time.decode(decoder1);
                }

        } finally {
            decoder0.decreaseStackDepth();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
        org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
        
        encoder0.encode(this.persisted, 8, 0);
        
        encoder0.encode(this.hasPersisted, 8, 1);
        
        encoder0.encode(this.hasDurability, 8, 2);
        
        encoder0.encode(this.hasQuota, 8, 3);
        
        encoder0.encode(this.durability, 12);
        
        encoder0.encode(this.quota, 16);
        
        encoder0.encode(this.expires, 24, true);
    }
}