// StableCdmContext.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/mojom/stable/stable_video_decoder.mojom
//

package org.chromium.media.stable.mojom;

import androidx.annotation.IntDef;


public interface StableCdmContext extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends StableCdmContext, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<StableCdmContext, StableCdmContext.Proxy> MANAGER = StableCdmContext_Internal.MANAGER;

}
