// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merchant_trust_signals.proto

package org.chromium.chrome.browser.merchant_viewer.proto;

public final class MerchantTrustSignalsOuterClass {
  private MerchantTrustSignalsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MerchantTrustSignalsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignals)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1 [deprecated = true];</code>
     * @return Whether the merchantStarRating field is set.
     */
    @java.lang.Deprecated boolean hasMerchantStarRating();
    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1 [deprecated = true];</code>
     * @return The merchantStarRating.
     */
    @java.lang.Deprecated float getMerchantStarRating();

    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2 [deprecated = true];</code>
     * @return Whether the merchantCountRating field is set.
     */
    @java.lang.Deprecated boolean hasMerchantCountRating();
    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2 [deprecated = true];</code>
     * @return The merchantCountRating.
     */
    @java.lang.Deprecated int getMerchantCountRating();

    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
     * @return Whether the merchantDetailsPageUrl field is set.
     */
    @java.lang.Deprecated boolean hasMerchantDetailsPageUrl();
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
     * @return The merchantDetailsPageUrl.
     */
    @java.lang.Deprecated java.lang.String getMerchantDetailsPageUrl();
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
     * @return The bytes for merchantDetailsPageUrl.
     */
    @java.lang.Deprecated com.google.protobuf.ByteString
        getMerchantDetailsPageUrlBytes();
  }
  /**
   * <pre>
   * Deprecated message. Use MerchantTrustSignalsV2 instead.
   * </pre>
   *
   * Protobuf type {@code org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignals}
   */
  public  static final class MerchantTrustSignals extends
      com.google.protobuf.GeneratedMessageLite<
          MerchantTrustSignals, MerchantTrustSignals.Builder> implements
      // @@protoc_insertion_point(message_implements:org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignals)
      MerchantTrustSignalsOrBuilder {
    private MerchantTrustSignals() {
      merchantDetailsPageUrl_ = "";
    }
    private int bitField0_;
    public static final int MERCHANT_STAR_RATING_FIELD_NUMBER = 1;
    private float merchantStarRating_;
    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1 [deprecated = true];</code>
     * @return Whether the merchantStarRating field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasMerchantStarRating() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1 [deprecated = true];</code>
     * @return The merchantStarRating.
     */
    @java.lang.Override
    @java.lang.Deprecated public float getMerchantStarRating() {
      return merchantStarRating_;
    }
    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1 [deprecated = true];</code>
     * @param value The merchantStarRating to set.
     */
    private void setMerchantStarRating(float value) {
      bitField0_ |= 0x00000001;
      merchantStarRating_ = value;
    }
    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1 [deprecated = true];</code>
     */
    private void clearMerchantStarRating() {
      bitField0_ = (bitField0_ & ~0x00000001);
      merchantStarRating_ = 0F;
    }

    public static final int MERCHANT_COUNT_RATING_FIELD_NUMBER = 2;
    private int merchantCountRating_;
    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2 [deprecated = true];</code>
     * @return Whether the merchantCountRating field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasMerchantCountRating() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2 [deprecated = true];</code>
     * @return The merchantCountRating.
     */
    @java.lang.Override
    @java.lang.Deprecated public int getMerchantCountRating() {
      return merchantCountRating_;
    }
    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2 [deprecated = true];</code>
     * @param value The merchantCountRating to set.
     */
    private void setMerchantCountRating(int value) {
      bitField0_ |= 0x00000002;
      merchantCountRating_ = value;
    }
    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2 [deprecated = true];</code>
     */
    private void clearMerchantCountRating() {
      bitField0_ = (bitField0_ & ~0x00000002);
      merchantCountRating_ = 0;
    }

    public static final int MERCHANT_DETAILS_PAGE_URL_FIELD_NUMBER = 3;
    private java.lang.String merchantDetailsPageUrl_;
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
     * @return Whether the merchantDetailsPageUrl field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasMerchantDetailsPageUrl() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
     * @return The merchantDetailsPageUrl.
     */
    @java.lang.Override
    @java.lang.Deprecated public java.lang.String getMerchantDetailsPageUrl() {
      return merchantDetailsPageUrl_;
    }
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
     * @return The bytes for merchantDetailsPageUrl.
     */
    @java.lang.Override
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getMerchantDetailsPageUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(merchantDetailsPageUrl_);
    }
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
     * @param value The merchantDetailsPageUrl to set.
     */
    private void setMerchantDetailsPageUrl(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000004;
      merchantDetailsPageUrl_ = value;
    }
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
     */
    private void clearMerchantDetailsPageUrl() {
      bitField0_ = (bitField0_ & ~0x00000004);
      merchantDetailsPageUrl_ = getDefaultInstance().getMerchantDetailsPageUrl();
    }
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
     * @param value The bytes for merchantDetailsPageUrl to set.
     */
    private void setMerchantDetailsPageUrlBytes(
        com.google.protobuf.ByteString value) {
      merchantDetailsPageUrl_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Deprecated message. Use MerchantTrustSignalsV2 instead.
     * </pre>
     *
     * Protobuf type {@code org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignals}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignals)
        org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsOrBuilder {
      // Construct using org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Overall rating out of 5.
       * </pre>
       *
       * <code>optional float merchant_star_rating = 1 [deprecated = true];</code>
       * @return Whether the merchantStarRating field is set.
       */
      @java.lang.Override
      @java.lang.Deprecated public boolean hasMerchantStarRating() {
        return instance.hasMerchantStarRating();
      }
      /**
       * <pre>
       * Overall rating out of 5.
       * </pre>
       *
       * <code>optional float merchant_star_rating = 1 [deprecated = true];</code>
       * @return The merchantStarRating.
       */
      @java.lang.Override
      @java.lang.Deprecated public float getMerchantStarRating() {
        return instance.getMerchantStarRating();
      }
      /**
       * <pre>
       * Overall rating out of 5.
       * </pre>
       *
       * <code>optional float merchant_star_rating = 1 [deprecated = true];</code>
       * @param value The merchantStarRating to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setMerchantStarRating(float value) {
        copyOnWrite();
        instance.setMerchantStarRating(value);
        return this;
      }
      /**
       * <pre>
       * Overall rating out of 5.
       * </pre>
       *
       * <code>optional float merchant_star_rating = 1 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearMerchantStarRating() {
        copyOnWrite();
        instance.clearMerchantStarRating();
        return this;
      }

      /**
       * <pre>
       * Total number of reviews.
       * </pre>
       *
       * <code>optional int32 merchant_count_rating = 2 [deprecated = true];</code>
       * @return Whether the merchantCountRating field is set.
       */
      @java.lang.Override
      @java.lang.Deprecated public boolean hasMerchantCountRating() {
        return instance.hasMerchantCountRating();
      }
      /**
       * <pre>
       * Total number of reviews.
       * </pre>
       *
       * <code>optional int32 merchant_count_rating = 2 [deprecated = true];</code>
       * @return The merchantCountRating.
       */
      @java.lang.Override
      @java.lang.Deprecated public int getMerchantCountRating() {
        return instance.getMerchantCountRating();
      }
      /**
       * <pre>
       * Total number of reviews.
       * </pre>
       *
       * <code>optional int32 merchant_count_rating = 2 [deprecated = true];</code>
       * @param value The merchantCountRating to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setMerchantCountRating(int value) {
        copyOnWrite();
        instance.setMerchantCountRating(value);
        return this;
      }
      /**
       * <pre>
       * Total number of reviews.
       * </pre>
       *
       * <code>optional int32 merchant_count_rating = 2 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearMerchantCountRating() {
        copyOnWrite();
        instance.clearMerchantCountRating();
        return this;
      }

      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
       * @return Whether the merchantDetailsPageUrl field is set.
       */
      @java.lang.Override
      @java.lang.Deprecated public boolean hasMerchantDetailsPageUrl() {
        return instance.hasMerchantDetailsPageUrl();
      }
      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
       * @return The merchantDetailsPageUrl.
       */
      @java.lang.Override
      @java.lang.Deprecated public java.lang.String getMerchantDetailsPageUrl() {
        return instance.getMerchantDetailsPageUrl();
      }
      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
       * @return The bytes for merchantDetailsPageUrl.
       */
      @java.lang.Override
      @java.lang.Deprecated public com.google.protobuf.ByteString
          getMerchantDetailsPageUrlBytes() {
        return instance.getMerchantDetailsPageUrlBytes();
      }
      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
       * @param value The merchantDetailsPageUrl to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setMerchantDetailsPageUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setMerchantDetailsPageUrl(value);
        return this;
      }
      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearMerchantDetailsPageUrl() {
        copyOnWrite();
        instance.clearMerchantDetailsPageUrl();
        return this;
      }
      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3 [deprecated = true];</code>
       * @param value The bytes for merchantDetailsPageUrl to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setMerchantDetailsPageUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMerchantDetailsPageUrlBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignals)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "merchantStarRating_",
              "merchantCountRating_",
              "merchantDetailsPageUrl_",
            };
            java.lang.String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1001\u0000\u0002" +
                "\u1004\u0001\u0003\u1008\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals> parser = PARSER;
          if (parser == null) {
            synchronized (org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignals)
    private static final org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals DEFAULT_INSTANCE;
    static {
      MerchantTrustSignals defaultInstance = new MerchantTrustSignals();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        MerchantTrustSignals.class, defaultInstance);
    }

    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignals getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MerchantTrustSignals> PARSER;

    public static com.google.protobuf.Parser<MerchantTrustSignals> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MerchantTrustSignalsV2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsV2)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1;</code>
     * @return Whether the merchantStarRating field is set.
     */
    boolean hasMerchantStarRating();
    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1;</code>
     * @return The merchantStarRating.
     */
    float getMerchantStarRating();

    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2;</code>
     * @return Whether the merchantCountRating field is set.
     */
    boolean hasMerchantCountRating();
    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2;</code>
     * @return The merchantCountRating.
     */
    int getMerchantCountRating();

    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3;</code>
     * @return Whether the merchantDetailsPageUrl field is set.
     */
    boolean hasMerchantDetailsPageUrl();
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3;</code>
     * @return The merchantDetailsPageUrl.
     */
    java.lang.String getMerchantDetailsPageUrl();
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3;</code>
     * @return The bytes for merchantDetailsPageUrl.
     */
    com.google.protobuf.ByteString
        getMerchantDetailsPageUrlBytes();

    /**
     * <pre>
     * Whether we have return policy for the merchant.
     * </pre>
     *
     * <code>optional bool has_return_policy = 4;</code>
     * @return Whether the hasReturnPolicy field is set.
     */
    boolean hasHasReturnPolicy();
    /**
     * <pre>
     * Whether we have return policy for the merchant.
     * </pre>
     *
     * <code>optional bool has_return_policy = 4;</code>
     * @return The hasReturnPolicy.
     */
    boolean getHasReturnPolicy();

    /**
     * <pre>
     * Non-personalized familiarity score of the merchant, ranged from 0 to 1.
     * </pre>
     *
     * <code>optional float non_personalized_familiarity_score = 5;</code>
     * @return Whether the nonPersonalizedFamiliarityScore field is set.
     */
    boolean hasNonPersonalizedFamiliarityScore();
    /**
     * <pre>
     * Non-personalized familiarity score of the merchant, ranged from 0 to 1.
     * </pre>
     *
     * <code>optional float non_personalized_familiarity_score = 5;</code>
     * @return The nonPersonalizedFamiliarityScore.
     */
    float getNonPersonalizedFamiliarityScore();

    /**
     * <pre>
     * Whether the merchant contains sensitive content.
     * </pre>
     *
     * <code>optional bool contains_sensitive_content = 6;</code>
     * @return Whether the containsSensitiveContent field is set.
     */
    boolean hasContainsSensitiveContent();
    /**
     * <pre>
     * Whether the merchant contains sensitive content.
     * </pre>
     *
     * <code>optional bool contains_sensitive_content = 6;</code>
     * @return The containsSensitiveContent.
     */
    boolean getContainsSensitiveContent();

    /**
     * <pre>
     * Whether proactively showing message is disabled for the merchant.
     * </pre>
     *
     * <code>optional bool proactive_message_disabled = 7;</code>
     * @return Whether the proactiveMessageDisabled field is set.
     */
    boolean hasProactiveMessageDisabled();
    /**
     * <pre>
     * Whether proactively showing message is disabled for the merchant.
     * </pre>
     *
     * <code>optional bool proactive_message_disabled = 7;</code>
     * @return The proactiveMessageDisabled.
     */
    boolean getProactiveMessageDisabled();
  }
  /**
   * Protobuf type {@code org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsV2}
   */
  public  static final class MerchantTrustSignalsV2 extends
      com.google.protobuf.GeneratedMessageLite<
          MerchantTrustSignalsV2, MerchantTrustSignalsV2.Builder> implements
      // @@protoc_insertion_point(message_implements:org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsV2)
      MerchantTrustSignalsV2OrBuilder {
    private MerchantTrustSignalsV2() {
      merchantDetailsPageUrl_ = "";
    }
    private int bitField0_;
    public static final int MERCHANT_STAR_RATING_FIELD_NUMBER = 1;
    private float merchantStarRating_;
    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1;</code>
     * @return Whether the merchantStarRating field is set.
     */
    @java.lang.Override
    public boolean hasMerchantStarRating() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1;</code>
     * @return The merchantStarRating.
     */
    @java.lang.Override
    public float getMerchantStarRating() {
      return merchantStarRating_;
    }
    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1;</code>
     * @param value The merchantStarRating to set.
     */
    private void setMerchantStarRating(float value) {
      bitField0_ |= 0x00000001;
      merchantStarRating_ = value;
    }
    /**
     * <pre>
     * Overall rating out of 5.
     * </pre>
     *
     * <code>optional float merchant_star_rating = 1;</code>
     */
    private void clearMerchantStarRating() {
      bitField0_ = (bitField0_ & ~0x00000001);
      merchantStarRating_ = 0F;
    }

    public static final int MERCHANT_COUNT_RATING_FIELD_NUMBER = 2;
    private int merchantCountRating_;
    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2;</code>
     * @return Whether the merchantCountRating field is set.
     */
    @java.lang.Override
    public boolean hasMerchantCountRating() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2;</code>
     * @return The merchantCountRating.
     */
    @java.lang.Override
    public int getMerchantCountRating() {
      return merchantCountRating_;
    }
    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2;</code>
     * @param value The merchantCountRating to set.
     */
    private void setMerchantCountRating(int value) {
      bitField0_ |= 0x00000002;
      merchantCountRating_ = value;
    }
    /**
     * <pre>
     * Total number of reviews.
     * </pre>
     *
     * <code>optional int32 merchant_count_rating = 2;</code>
     */
    private void clearMerchantCountRating() {
      bitField0_ = (bitField0_ & ~0x00000002);
      merchantCountRating_ = 0;
    }

    public static final int MERCHANT_DETAILS_PAGE_URL_FIELD_NUMBER = 3;
    private java.lang.String merchantDetailsPageUrl_;
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3;</code>
     * @return Whether the merchantDetailsPageUrl field is set.
     */
    @java.lang.Override
    public boolean hasMerchantDetailsPageUrl() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3;</code>
     * @return The merchantDetailsPageUrl.
     */
    @java.lang.Override
    public java.lang.String getMerchantDetailsPageUrl() {
      return merchantDetailsPageUrl_;
    }
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3;</code>
     * @return The bytes for merchantDetailsPageUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMerchantDetailsPageUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(merchantDetailsPageUrl_);
    }
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3;</code>
     * @param value The merchantDetailsPageUrl to set.
     */
    private void setMerchantDetailsPageUrl(
        java.lang.String value) {
      value.getClass();
  bitField0_ |= 0x00000004;
      merchantDetailsPageUrl_ = value;
    }
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3;</code>
     */
    private void clearMerchantDetailsPageUrl() {
      bitField0_ = (bitField0_ & ~0x00000004);
      merchantDetailsPageUrl_ = getDefaultInstance().getMerchantDetailsPageUrl();
    }
    /**
     * <pre>
     * Link to the merchant details page.
     * </pre>
     *
     * <code>optional string merchant_details_page_url = 3;</code>
     * @param value The bytes for merchantDetailsPageUrl to set.
     */
    private void setMerchantDetailsPageUrlBytes(
        com.google.protobuf.ByteString value) {
      merchantDetailsPageUrl_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static final int HAS_RETURN_POLICY_FIELD_NUMBER = 4;
    private boolean hasReturnPolicy_;
    /**
     * <pre>
     * Whether we have return policy for the merchant.
     * </pre>
     *
     * <code>optional bool has_return_policy = 4;</code>
     * @return Whether the hasReturnPolicy field is set.
     */
    @java.lang.Override
    public boolean hasHasReturnPolicy() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Whether we have return policy for the merchant.
     * </pre>
     *
     * <code>optional bool has_return_policy = 4;</code>
     * @return The hasReturnPolicy.
     */
    @java.lang.Override
    public boolean getHasReturnPolicy() {
      return hasReturnPolicy_;
    }
    /**
     * <pre>
     * Whether we have return policy for the merchant.
     * </pre>
     *
     * <code>optional bool has_return_policy = 4;</code>
     * @param value The hasReturnPolicy to set.
     */
    private void setHasReturnPolicy(boolean value) {
      bitField0_ |= 0x00000008;
      hasReturnPolicy_ = value;
    }
    /**
     * <pre>
     * Whether we have return policy for the merchant.
     * </pre>
     *
     * <code>optional bool has_return_policy = 4;</code>
     */
    private void clearHasReturnPolicy() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hasReturnPolicy_ = false;
    }

    public static final int NON_PERSONALIZED_FAMILIARITY_SCORE_FIELD_NUMBER = 5;
    private float nonPersonalizedFamiliarityScore_;
    /**
     * <pre>
     * Non-personalized familiarity score of the merchant, ranged from 0 to 1.
     * </pre>
     *
     * <code>optional float non_personalized_familiarity_score = 5;</code>
     * @return Whether the nonPersonalizedFamiliarityScore field is set.
     */
    @java.lang.Override
    public boolean hasNonPersonalizedFamiliarityScore() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Non-personalized familiarity score of the merchant, ranged from 0 to 1.
     * </pre>
     *
     * <code>optional float non_personalized_familiarity_score = 5;</code>
     * @return The nonPersonalizedFamiliarityScore.
     */
    @java.lang.Override
    public float getNonPersonalizedFamiliarityScore() {
      return nonPersonalizedFamiliarityScore_;
    }
    /**
     * <pre>
     * Non-personalized familiarity score of the merchant, ranged from 0 to 1.
     * </pre>
     *
     * <code>optional float non_personalized_familiarity_score = 5;</code>
     * @param value The nonPersonalizedFamiliarityScore to set.
     */
    private void setNonPersonalizedFamiliarityScore(float value) {
      bitField0_ |= 0x00000010;
      nonPersonalizedFamiliarityScore_ = value;
    }
    /**
     * <pre>
     * Non-personalized familiarity score of the merchant, ranged from 0 to 1.
     * </pre>
     *
     * <code>optional float non_personalized_familiarity_score = 5;</code>
     */
    private void clearNonPersonalizedFamiliarityScore() {
      bitField0_ = (bitField0_ & ~0x00000010);
      nonPersonalizedFamiliarityScore_ = 0F;
    }

    public static final int CONTAINS_SENSITIVE_CONTENT_FIELD_NUMBER = 6;
    private boolean containsSensitiveContent_;
    /**
     * <pre>
     * Whether the merchant contains sensitive content.
     * </pre>
     *
     * <code>optional bool contains_sensitive_content = 6;</code>
     * @return Whether the containsSensitiveContent field is set.
     */
    @java.lang.Override
    public boolean hasContainsSensitiveContent() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Whether the merchant contains sensitive content.
     * </pre>
     *
     * <code>optional bool contains_sensitive_content = 6;</code>
     * @return The containsSensitiveContent.
     */
    @java.lang.Override
    public boolean getContainsSensitiveContent() {
      return containsSensitiveContent_;
    }
    /**
     * <pre>
     * Whether the merchant contains sensitive content.
     * </pre>
     *
     * <code>optional bool contains_sensitive_content = 6;</code>
     * @param value The containsSensitiveContent to set.
     */
    private void setContainsSensitiveContent(boolean value) {
      bitField0_ |= 0x00000020;
      containsSensitiveContent_ = value;
    }
    /**
     * <pre>
     * Whether the merchant contains sensitive content.
     * </pre>
     *
     * <code>optional bool contains_sensitive_content = 6;</code>
     */
    private void clearContainsSensitiveContent() {
      bitField0_ = (bitField0_ & ~0x00000020);
      containsSensitiveContent_ = false;
    }

    public static final int PROACTIVE_MESSAGE_DISABLED_FIELD_NUMBER = 7;
    private boolean proactiveMessageDisabled_;
    /**
     * <pre>
     * Whether proactively showing message is disabled for the merchant.
     * </pre>
     *
     * <code>optional bool proactive_message_disabled = 7;</code>
     * @return Whether the proactiveMessageDisabled field is set.
     */
    @java.lang.Override
    public boolean hasProactiveMessageDisabled() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Whether proactively showing message is disabled for the merchant.
     * </pre>
     *
     * <code>optional bool proactive_message_disabled = 7;</code>
     * @return The proactiveMessageDisabled.
     */
    @java.lang.Override
    public boolean getProactiveMessageDisabled() {
      return proactiveMessageDisabled_;
    }
    /**
     * <pre>
     * Whether proactively showing message is disabled for the merchant.
     * </pre>
     *
     * <code>optional bool proactive_message_disabled = 7;</code>
     * @param value The proactiveMessageDisabled to set.
     */
    private void setProactiveMessageDisabled(boolean value) {
      bitField0_ |= 0x00000040;
      proactiveMessageDisabled_ = value;
    }
    /**
     * <pre>
     * Whether proactively showing message is disabled for the merchant.
     * </pre>
     *
     * <code>optional bool proactive_message_disabled = 7;</code>
     */
    private void clearProactiveMessageDisabled() {
      bitField0_ = (bitField0_ & ~0x00000040);
      proactiveMessageDisabled_ = false;
    }

    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsV2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsV2)
        org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2OrBuilder {
      // Construct using org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Overall rating out of 5.
       * </pre>
       *
       * <code>optional float merchant_star_rating = 1;</code>
       * @return Whether the merchantStarRating field is set.
       */
      @java.lang.Override
      public boolean hasMerchantStarRating() {
        return instance.hasMerchantStarRating();
      }
      /**
       * <pre>
       * Overall rating out of 5.
       * </pre>
       *
       * <code>optional float merchant_star_rating = 1;</code>
       * @return The merchantStarRating.
       */
      @java.lang.Override
      public float getMerchantStarRating() {
        return instance.getMerchantStarRating();
      }
      /**
       * <pre>
       * Overall rating out of 5.
       * </pre>
       *
       * <code>optional float merchant_star_rating = 1;</code>
       * @param value The merchantStarRating to set.
       * @return This builder for chaining.
       */
      public Builder setMerchantStarRating(float value) {
        copyOnWrite();
        instance.setMerchantStarRating(value);
        return this;
      }
      /**
       * <pre>
       * Overall rating out of 5.
       * </pre>
       *
       * <code>optional float merchant_star_rating = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMerchantStarRating() {
        copyOnWrite();
        instance.clearMerchantStarRating();
        return this;
      }

      /**
       * <pre>
       * Total number of reviews.
       * </pre>
       *
       * <code>optional int32 merchant_count_rating = 2;</code>
       * @return Whether the merchantCountRating field is set.
       */
      @java.lang.Override
      public boolean hasMerchantCountRating() {
        return instance.hasMerchantCountRating();
      }
      /**
       * <pre>
       * Total number of reviews.
       * </pre>
       *
       * <code>optional int32 merchant_count_rating = 2;</code>
       * @return The merchantCountRating.
       */
      @java.lang.Override
      public int getMerchantCountRating() {
        return instance.getMerchantCountRating();
      }
      /**
       * <pre>
       * Total number of reviews.
       * </pre>
       *
       * <code>optional int32 merchant_count_rating = 2;</code>
       * @param value The merchantCountRating to set.
       * @return This builder for chaining.
       */
      public Builder setMerchantCountRating(int value) {
        copyOnWrite();
        instance.setMerchantCountRating(value);
        return this;
      }
      /**
       * <pre>
       * Total number of reviews.
       * </pre>
       *
       * <code>optional int32 merchant_count_rating = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMerchantCountRating() {
        copyOnWrite();
        instance.clearMerchantCountRating();
        return this;
      }

      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3;</code>
       * @return Whether the merchantDetailsPageUrl field is set.
       */
      @java.lang.Override
      public boolean hasMerchantDetailsPageUrl() {
        return instance.hasMerchantDetailsPageUrl();
      }
      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3;</code>
       * @return The merchantDetailsPageUrl.
       */
      @java.lang.Override
      public java.lang.String getMerchantDetailsPageUrl() {
        return instance.getMerchantDetailsPageUrl();
      }
      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3;</code>
       * @return The bytes for merchantDetailsPageUrl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMerchantDetailsPageUrlBytes() {
        return instance.getMerchantDetailsPageUrlBytes();
      }
      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3;</code>
       * @param value The merchantDetailsPageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setMerchantDetailsPageUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setMerchantDetailsPageUrl(value);
        return this;
      }
      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMerchantDetailsPageUrl() {
        copyOnWrite();
        instance.clearMerchantDetailsPageUrl();
        return this;
      }
      /**
       * <pre>
       * Link to the merchant details page.
       * </pre>
       *
       * <code>optional string merchant_details_page_url = 3;</code>
       * @param value The bytes for merchantDetailsPageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setMerchantDetailsPageUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMerchantDetailsPageUrlBytes(value);
        return this;
      }

      /**
       * <pre>
       * Whether we have return policy for the merchant.
       * </pre>
       *
       * <code>optional bool has_return_policy = 4;</code>
       * @return Whether the hasReturnPolicy field is set.
       */
      @java.lang.Override
      public boolean hasHasReturnPolicy() {
        return instance.hasHasReturnPolicy();
      }
      /**
       * <pre>
       * Whether we have return policy for the merchant.
       * </pre>
       *
       * <code>optional bool has_return_policy = 4;</code>
       * @return The hasReturnPolicy.
       */
      @java.lang.Override
      public boolean getHasReturnPolicy() {
        return instance.getHasReturnPolicy();
      }
      /**
       * <pre>
       * Whether we have return policy for the merchant.
       * </pre>
       *
       * <code>optional bool has_return_policy = 4;</code>
       * @param value The hasReturnPolicy to set.
       * @return This builder for chaining.
       */
      public Builder setHasReturnPolicy(boolean value) {
        copyOnWrite();
        instance.setHasReturnPolicy(value);
        return this;
      }
      /**
       * <pre>
       * Whether we have return policy for the merchant.
       * </pre>
       *
       * <code>optional bool has_return_policy = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasReturnPolicy() {
        copyOnWrite();
        instance.clearHasReturnPolicy();
        return this;
      }

      /**
       * <pre>
       * Non-personalized familiarity score of the merchant, ranged from 0 to 1.
       * </pre>
       *
       * <code>optional float non_personalized_familiarity_score = 5;</code>
       * @return Whether the nonPersonalizedFamiliarityScore field is set.
       */
      @java.lang.Override
      public boolean hasNonPersonalizedFamiliarityScore() {
        return instance.hasNonPersonalizedFamiliarityScore();
      }
      /**
       * <pre>
       * Non-personalized familiarity score of the merchant, ranged from 0 to 1.
       * </pre>
       *
       * <code>optional float non_personalized_familiarity_score = 5;</code>
       * @return The nonPersonalizedFamiliarityScore.
       */
      @java.lang.Override
      public float getNonPersonalizedFamiliarityScore() {
        return instance.getNonPersonalizedFamiliarityScore();
      }
      /**
       * <pre>
       * Non-personalized familiarity score of the merchant, ranged from 0 to 1.
       * </pre>
       *
       * <code>optional float non_personalized_familiarity_score = 5;</code>
       * @param value The nonPersonalizedFamiliarityScore to set.
       * @return This builder for chaining.
       */
      public Builder setNonPersonalizedFamiliarityScore(float value) {
        copyOnWrite();
        instance.setNonPersonalizedFamiliarityScore(value);
        return this;
      }
      /**
       * <pre>
       * Non-personalized familiarity score of the merchant, ranged from 0 to 1.
       * </pre>
       *
       * <code>optional float non_personalized_familiarity_score = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonPersonalizedFamiliarityScore() {
        copyOnWrite();
        instance.clearNonPersonalizedFamiliarityScore();
        return this;
      }

      /**
       * <pre>
       * Whether the merchant contains sensitive content.
       * </pre>
       *
       * <code>optional bool contains_sensitive_content = 6;</code>
       * @return Whether the containsSensitiveContent field is set.
       */
      @java.lang.Override
      public boolean hasContainsSensitiveContent() {
        return instance.hasContainsSensitiveContent();
      }
      /**
       * <pre>
       * Whether the merchant contains sensitive content.
       * </pre>
       *
       * <code>optional bool contains_sensitive_content = 6;</code>
       * @return The containsSensitiveContent.
       */
      @java.lang.Override
      public boolean getContainsSensitiveContent() {
        return instance.getContainsSensitiveContent();
      }
      /**
       * <pre>
       * Whether the merchant contains sensitive content.
       * </pre>
       *
       * <code>optional bool contains_sensitive_content = 6;</code>
       * @param value The containsSensitiveContent to set.
       * @return This builder for chaining.
       */
      public Builder setContainsSensitiveContent(boolean value) {
        copyOnWrite();
        instance.setContainsSensitiveContent(value);
        return this;
      }
      /**
       * <pre>
       * Whether the merchant contains sensitive content.
       * </pre>
       *
       * <code>optional bool contains_sensitive_content = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearContainsSensitiveContent() {
        copyOnWrite();
        instance.clearContainsSensitiveContent();
        return this;
      }

      /**
       * <pre>
       * Whether proactively showing message is disabled for the merchant.
       * </pre>
       *
       * <code>optional bool proactive_message_disabled = 7;</code>
       * @return Whether the proactiveMessageDisabled field is set.
       */
      @java.lang.Override
      public boolean hasProactiveMessageDisabled() {
        return instance.hasProactiveMessageDisabled();
      }
      /**
       * <pre>
       * Whether proactively showing message is disabled for the merchant.
       * </pre>
       *
       * <code>optional bool proactive_message_disabled = 7;</code>
       * @return The proactiveMessageDisabled.
       */
      @java.lang.Override
      public boolean getProactiveMessageDisabled() {
        return instance.getProactiveMessageDisabled();
      }
      /**
       * <pre>
       * Whether proactively showing message is disabled for the merchant.
       * </pre>
       *
       * <code>optional bool proactive_message_disabled = 7;</code>
       * @param value The proactiveMessageDisabled to set.
       * @return This builder for chaining.
       */
      public Builder setProactiveMessageDisabled(boolean value) {
        copyOnWrite();
        instance.setProactiveMessageDisabled(value);
        return this;
      }
      /**
       * <pre>
       * Whether proactively showing message is disabled for the merchant.
       * </pre>
       *
       * <code>optional bool proactive_message_disabled = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearProactiveMessageDisabled() {
        copyOnWrite();
        instance.clearProactiveMessageDisabled();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsV2)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "merchantStarRating_",
              "merchantCountRating_",
              "merchantDetailsPageUrl_",
              "hasReturnPolicy_",
              "nonPersonalizedFamiliarityScore_",
              "containsSensitiveContent_",
              "proactiveMessageDisabled_",
            };
            java.lang.String info =
                "\u0001\u0007\u0000\u0001\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u1001\u0000\u0002" +
                "\u1004\u0001\u0003\u1008\u0002\u0004\u1007\u0003\u0005\u1001\u0004\u0006\u1007\u0005" +
                "\u0007\u1007\u0006";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2> parser = PARSER;
          if (parser == null) {
            synchronized (org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsV2)
    private static final org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 DEFAULT_INSTANCE;
    static {
      MerchantTrustSignalsV2 defaultInstance = new MerchantTrustSignalsV2();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        MerchantTrustSignalsV2.class, defaultInstance);
    }

    public static org.chromium.chrome.browser.merchant_viewer.proto.MerchantTrustSignalsOuterClass.MerchantTrustSignalsV2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MerchantTrustSignalsV2> PARSER;

    public static com.google.protobuf.Parser<MerchantTrustSignalsV2> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
