// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: browser/service.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

public interface RegisterPasswordResetRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autofill_assistant.RegisterPasswordResetRequestProto)
    com.google.protobuf.MessageLiteOrBuilder {
}
