// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chrome/browser/power_bookmarks/proto/shopping_specifics.proto

package org.chromium.chrome.browser.power_bookmarks;

public final class ShoppingSpecificsOuterClass {
  private ShoppingSpecificsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
