// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/list_passwords_result.proto

package org.chromium.components.sync.protocol;

/**
 * <pre>
 * Response to a request sent to Google Mobile Services to request a list of
 * passwords.
 * ATTENTION(crbug.com/1330911): This proto is being moved to
 * components/password_manager/core/browser/protocol folder. Two files exist
 * while the migration is in process, this file will be deleted when the
 * migration is over. IF YOU MODIFY THIS FILE, PLEASE ALSO MODIFY THE COPY IN
 * components/password_manager.
 * </pre>
 *
 * Protobuf type {@code sync_pb.ListPasswordsResult}
 */
public  final class ListPasswordsResult extends
    com.google.protobuf.GeneratedMessageLite<
        ListPasswordsResult, ListPasswordsResult.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.ListPasswordsResult)
    ListPasswordsResultOrBuilder {
  private ListPasswordsResult() {
    passwordData_ = emptyProtobufList();
  }
  public static final int PASSWORD_DATA_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<org.chromium.components.sync.protocol.PasswordWithLocalData> passwordData_;
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.chromium.components.sync.protocol.PasswordWithLocalData> getPasswordDataList() {
    return passwordData_;
  }
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  public java.util.List<? extends org.chromium.components.sync.protocol.PasswordWithLocalDataOrBuilder> 
      getPasswordDataOrBuilderList() {
    return passwordData_;
  }
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  @java.lang.Override
  public int getPasswordDataCount() {
    return passwordData_.size();
  }
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  @java.lang.Override
  public org.chromium.components.sync.protocol.PasswordWithLocalData getPasswordData(int index) {
    return passwordData_.get(index);
  }
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  public org.chromium.components.sync.protocol.PasswordWithLocalDataOrBuilder getPasswordDataOrBuilder(
      int index) {
    return passwordData_.get(index);
  }
  private void ensurePasswordDataIsMutable() {
    com.google.protobuf.Internal.ProtobufList<org.chromium.components.sync.protocol.PasswordWithLocalData> tmp = passwordData_;
    if (!tmp.isModifiable()) {
      passwordData_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  private void setPasswordData(
      int index, org.chromium.components.sync.protocol.PasswordWithLocalData value) {
    value.getClass();
  ensurePasswordDataIsMutable();
    passwordData_.set(index, value);
  }
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  private void addPasswordData(org.chromium.components.sync.protocol.PasswordWithLocalData value) {
    value.getClass();
  ensurePasswordDataIsMutable();
    passwordData_.add(value);
  }
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  private void addPasswordData(
      int index, org.chromium.components.sync.protocol.PasswordWithLocalData value) {
    value.getClass();
  ensurePasswordDataIsMutable();
    passwordData_.add(index, value);
  }
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  private void addAllPasswordData(
      java.lang.Iterable<? extends org.chromium.components.sync.protocol.PasswordWithLocalData> values) {
    ensurePasswordDataIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, passwordData_);
  }
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  private void clearPasswordData() {
    passwordData_ = emptyProtobufList();
  }
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  private void removePasswordData(int index) {
    ensurePasswordDataIsMutable();
    passwordData_.remove(index);
  }

  public static org.chromium.components.sync.protocol.ListPasswordsResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ListPasswordsResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.ListPasswordsResult prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Response to a request sent to Google Mobile Services to request a list of
   * passwords.
   * ATTENTION(crbug.com/1330911): This proto is being moved to
   * components/password_manager/core/browser/protocol folder. Two files exist
   * while the migration is in process, this file will be deleted when the
   * migration is over. IF YOU MODIFY THIS FILE, PLEASE ALSO MODIFY THE COPY IN
   * components/password_manager.
   * </pre>
   *
   * Protobuf type {@code sync_pb.ListPasswordsResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.ListPasswordsResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.ListPasswordsResult)
      org.chromium.components.sync.protocol.ListPasswordsResultOrBuilder {
    // Construct using org.chromium.components.sync.protocol.ListPasswordsResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.chromium.components.sync.protocol.PasswordWithLocalData> getPasswordDataList() {
      return java.util.Collections.unmodifiableList(
          instance.getPasswordDataList());
    }
    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    @java.lang.Override
    public int getPasswordDataCount() {
      return instance.getPasswordDataCount();
    }/**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    @java.lang.Override
    public org.chromium.components.sync.protocol.PasswordWithLocalData getPasswordData(int index) {
      return instance.getPasswordData(index);
    }
    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    public Builder setPasswordData(
        int index, org.chromium.components.sync.protocol.PasswordWithLocalData value) {
      copyOnWrite();
      instance.setPasswordData(index, value);
      return this;
    }
    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    public Builder setPasswordData(
        int index, org.chromium.components.sync.protocol.PasswordWithLocalData.Builder builderForValue) {
      copyOnWrite();
      instance.setPasswordData(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    public Builder addPasswordData(org.chromium.components.sync.protocol.PasswordWithLocalData value) {
      copyOnWrite();
      instance.addPasswordData(value);
      return this;
    }
    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    public Builder addPasswordData(
        int index, org.chromium.components.sync.protocol.PasswordWithLocalData value) {
      copyOnWrite();
      instance.addPasswordData(index, value);
      return this;
    }
    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    public Builder addPasswordData(
        org.chromium.components.sync.protocol.PasswordWithLocalData.Builder builderForValue) {
      copyOnWrite();
      instance.addPasswordData(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    public Builder addPasswordData(
        int index, org.chromium.components.sync.protocol.PasswordWithLocalData.Builder builderForValue) {
      copyOnWrite();
      instance.addPasswordData(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    public Builder addAllPasswordData(
        java.lang.Iterable<? extends org.chromium.components.sync.protocol.PasswordWithLocalData> values) {
      copyOnWrite();
      instance.addAllPasswordData(values);
      return this;
    }
    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    public Builder clearPasswordData() {
      copyOnWrite();
      instance.clearPasswordData();
      return this;
    }
    /**
     * <pre>
     * The list of password entries and corresponding additional info.
     * </pre>
     *
     * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
     */
    public Builder removePasswordData(int index) {
      copyOnWrite();
      instance.removePasswordData(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.ListPasswordsResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.ListPasswordsResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "passwordData_",
            org.chromium.components.sync.protocol.PasswordWithLocalData.class,
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.chromium.components.sync.protocol.ListPasswordsResult> parser = PARSER;
        if (parser == null) {
          synchronized (org.chromium.components.sync.protocol.ListPasswordsResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.chromium.components.sync.protocol.ListPasswordsResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.ListPasswordsResult)
  private static final org.chromium.components.sync.protocol.ListPasswordsResult DEFAULT_INSTANCE;
  static {
    ListPasswordsResult defaultInstance = new ListPasswordsResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListPasswordsResult.class, defaultInstance);
  }

  public static org.chromium.components.sync.protocol.ListPasswordsResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListPasswordsResult> PARSER;

  public static com.google.protobuf.Parser<ListPasswordsResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

