// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/list_passwords_result.proto

package org.chromium.components.sync.protocol;

public final class ListPasswordsResultOuterClass {
  private ListPasswordsResultOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
