// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/list_passwords_result.proto

package org.chromium.components.sync.protocol;

public interface ListPasswordsResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.ListPasswordsResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  java.util.List<org.chromium.components.sync.protocol.PasswordWithLocalData> 
      getPasswordDataList();
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  org.chromium.components.sync.protocol.PasswordWithLocalData getPasswordData(int index);
  /**
   * <pre>
   * The list of password entries and corresponding additional info.
   * </pre>
   *
   * <code>repeated .sync_pb.PasswordWithLocalData password_data = 1;</code>
   */
  int getPasswordDataCount();
}
