// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components/sync/protocol/password_with_local_data.proto

package org.chromium.components.sync.protocol;

public interface PasswordWithLocalDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.PasswordWithLocalData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * A potentially synced set of credentials.
   * </pre>
   *
   * <code>optional .sync_pb.PasswordSpecificsData password_specifics_data = 1;</code>
   * @return Whether the passwordSpecificsData field is set.
   */
  boolean hasPasswordSpecificsData();
  /**
   * <pre>
   * A potentially synced set of credentials.
   * </pre>
   *
   * <code>optional .sync_pb.PasswordSpecificsData password_specifics_data = 1;</code>
   * @return The passwordSpecificsData.
   */
  org.chromium.components.sync.protocol.PasswordSpecificsData getPasswordSpecificsData();

  /**
   * <code>optional .sync_pb.PasswordWithLocalData.LocalData local_data = 3;</code>
   * @return Whether the localData field is set.
   */
  boolean hasLocalData();
  /**
   * <code>optional .sync_pb.PasswordWithLocalData.LocalData local_data = 3;</code>
   * @return The localData.
   */
  org.chromium.components.sync.protocol.PasswordWithLocalData.LocalData getLocalData();
}
